# Generated by Django 3.1.2 on 2022-07-03 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_contacto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacto',
            name='tipo_consulta',
        ),
    ]
